### PR TITLE
Solving issues number #1289 and #231

### PR DESCRIPTION
**Pull request by amroahmed90**
Solved issues with the color legend component in webviz as well as added a new prop "cssLegendStyles" that takes css styles and applies them to the color legend.

### CODE REVIEW

**Comment by shruthirai** [comment]
@amroahmed90 I see that there are few commented codes in the files. Can you please delete it, if not used.

**Comment by shruthirai** [comment]
Earlier clicking anywhere outside used to close the accordion but its not happening now. Is it expected ?

**Comment by amroahmed90** [comment]
are you setting the isModal prop to true?

**Comment by shruthirai** [comment]
> are you setting the isModal prop to true?

Ok, after setting it to true, it works.

**Comment by shruthirai** [comment]
@amroahmed90 What does this prop does "isOpenProp" ?

**Comment by shruthirai** [comment]
image
 I see like this in webviz default storybook

**Comment by shruthirai** [comment]
@amroahmed90 lets merge this PR and rest of the issue we discussed can go with other PR

**Review by shruthirai — APPROVED** [review]

**Pull request merged**
